"""add attributes real scheme rules depend on

Revision ID: 0eac4115262c
Revises: 3f4ad9c3d67a
Create Date: 2026-08-29 17:38:27.832972
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0eac4115262c'
down_revision: Union[str, None] = '3f4ad9c3d67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Widen the model so real government eligibility rules can be expressed.

    Researching actual central and Maharashtra schemes showed that almost none
    decide eligibility on age and income alone: Ramai Awas is Scheduled Caste
    only, MJPJAY keys off ration card colour, Birsa Munda off land holding, and
    Sanjay Gandhi Niradhar on "income under Rs 21,000 OR on the BPL list".

    The NOT NULL columns carry server defaults so they can be added to tables
    that already hold rows.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizens', sa.Column('social_category', sa.String(length=20), nullable=True))
    op.add_column('citizens', sa.Column('is_bpl', sa.Boolean(), nullable=False,
                                        server_default=sa.false()))
    op.add_column('citizens', sa.Column('secc_listed', sa.Boolean(), nullable=False,
                                        server_default=sa.false()))
    op.add_column('citizens', sa.Column('ration_card_type', sa.String(length=20), nullable=True))
    op.add_column('citizens', sa.Column('land_holding_hectares', sa.Float(), nullable=True))
    op.add_column('citizens', sa.Column('marital_status', sa.String(length=20), nullable=True))
    op.add_column('citizens', sa.Column('disability_percent', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_citizens_social_category'), 'citizens', ['social_category'], unique=False)
    op.add_column('schemes', sa.Column('level', sa.String(length=20), nullable=False,
                                       server_default='state'))
    op.add_column('schemes', sa.Column('category', sa.String(length=60), nullable=True))
    op.add_column('schemes', sa.Column('announced_on', sa.Date(), nullable=True))
    op.add_column('schemes', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('schemes', sa.Column('confidence', sa.String(length=20), nullable=False,
                                       server_default='medium'))
    op.add_column('schemes', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_schemes_announced_on'), 'schemes', ['announced_on'], unique=False)
    op.create_index(op.f('ix_schemes_category'), 'schemes', ['category'], unique=False)
    op.create_index(op.f('ix_schemes_level'), 'schemes', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schemes_level'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_category'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_announced_on'), table_name='schemes')
    op.drop_column('schemes', 'notes')
    op.drop_column('schemes', 'confidence')
    op.drop_column('schemes', 'source_url')
    op.drop_column('schemes', 'announced_on')
    op.drop_column('schemes', 'category')
    op.drop_column('schemes', 'level')
    op.drop_index(op.f('ix_citizens_social_category'), table_name='citizens')
    op.drop_column('citizens', 'disability_percent')
    op.drop_column('citizens', 'marital_status')
    op.drop_column('citizens', 'land_holding_hectares')
    op.drop_column('citizens', 'ration_card_type')
    op.drop_column('citizens', 'secc_listed')
    op.drop_column('citizens', 'is_bpl')
    op.drop_column('citizens', 'social_category')
    # ### end Alembic commands ###
