"""initial schema

Revision ID: 3f4ad9c3d67a
Revises: 
Create Date: 2026-08-29 15:02:21.924886
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3f4ad9c3d67a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_mr', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.String(length=40), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('ward', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('details_mr', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_facility_type'), 'facilities', ['facility_type'], unique=False)
    op.create_table('families',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_mr', sa.String(length=255), nullable=False),
    sa.Column('ward', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('address_mr', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_mr', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_chunk_entity')
    )
    op.create_index(op.f('ix_knowledge_chunks_entity_type'), 'knowledge_chunks', ['entity_type'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_mr', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_mr', sa.Text(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('utilized', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_mr', sa.String(length=30), nullable=False),
    sa.Column('ward', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('location_mr', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_completion', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_ward'), 'projects', ['ward'], unique=False)
    op.create_table('sabha_meetings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_mr', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('summary_mr', sa.Text(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('decisions_mr', sa.JSON(), nullable=False),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('extracted_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sabha_meetings_meeting_date'), 'sabha_meetings', ['meeting_date'], unique=False)
    op.create_table('schemes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_mr', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_mr', sa.Text(), nullable=False),
    sa.Column('benefit', sa.String(length=255), nullable=False),
    sa.Column('benefit_mr', sa.String(length=255), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('required_documents', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_government_feed', sa.Boolean(), nullable=False),
    sa.Column('source_gov', sa.String(length=255), nullable=True),
    sa.Column('form_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citizens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_mr', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('gender_mr', sa.String(length=20), nullable=False),
    sa.Column('occupation', sa.String(length=120), nullable=False),
    sa.Column('occupation_mr', sa.String(length=120), nullable=False),
    sa.Column('income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ward', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('family_id', sa.String(length=64), nullable=True),
    sa.Column('relation', sa.String(length=80), nullable=True),
    sa.Column('relation_mr', sa.String(length=80), nullable=True),
    sa.Column('is_head', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizens_family_id'), 'citizens', ['family_id'], unique=False)
    op.create_index(op.f('ix_citizens_name'), 'citizens', ['name'], unique=False)
    op.create_index(op.f('ix_citizens_ward'), 'citizens', ['ward'], unique=False)
    op.create_table('sabha_action_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('meeting_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('action_mr', sa.Text(), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=False),
    sa.Column('responsible_mr', sa.String(length=255), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_mr', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['sabha_meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sabha_action_items_meeting_id'), 'sabha_action_items', ['meeting_id'], unique=False)
    op.create_table('grievances',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_mr', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_mr', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('category_mr', sa.String(length=60), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('priority_mr', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_mr', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('department_mr', sa.String(length=120), nullable=False),
    sa.Column('ward', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('citizen_id', sa.String(length=64), nullable=True),
    sa.Column('citizen_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('submitted_date', sa.Date(), nullable=False),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.Column('officer_notes', sa.Text(), nullable=True),
    sa.Column('auto_classified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_category'), 'grievances', ['category'], unique=False)
    op.create_index(op.f('ix_grievances_citizen_id'), 'grievances', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_grievances_priority'), 'grievances', ['priority'], unique=False)
    op.create_index(op.f('ix_grievances_status'), 'grievances', ['status'], unique=False)
    op.create_index(op.f('ix_grievances_ward'), 'grievances', ['ward'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('citizen_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('citizen_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('citizen_id', sa.String(length=64), nullable=False),
    sa.Column('doc_type', sa.String(length=120), nullable=False),
    sa.Column('doc_type_mr', sa.String(length=120), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('status_mr', sa.String(length=40), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.String(length=64), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_documents_citizen_id'), 'citizen_documents', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_citizen_documents_status'), 'citizen_documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizen_documents_status'), table_name='citizen_documents')
    op.drop_index(op.f('ix_citizen_documents_citizen_id'), table_name='citizen_documents')
    op.drop_table('citizen_documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_grievances_ward'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_status'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_priority'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_citizen_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_category'), table_name='grievances')
    op.drop_table('grievances')
    op.drop_index(op.f('ix_sabha_action_items_meeting_id'), table_name='sabha_action_items')
    op.drop_table('sabha_action_items')
    op.drop_index(op.f('ix_citizens_ward'), table_name='citizens')
    op.drop_index(op.f('ix_citizens_name'), table_name='citizens')
    op.drop_index(op.f('ix_citizens_family_id'), table_name='citizens')
    op.drop_table('citizens')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_sabha_meetings_meeting_date'), table_name='sabha_meetings')
    op.drop_table('sabha_meetings')
    op.drop_index(op.f('ix_projects_ward'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_knowledge_chunks_entity_type'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('families')
    op.drop_index(op.f('ix_facilities_facility_type'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
