"""add grievance history

Revision ID: 9a7efc2bf349
Revises: ef791b37d385
Create Date: 2026-08-30 06:45:59.411481
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a7efc2bf349'
down_revision: Union[str, None] = 'ef791b37d385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grievance_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('grievance_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('note_mr', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_events_created_at'), 'grievance_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_grievance_events_grievance_id'), 'grievance_events', ['grievance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grievance_events_grievance_id'), table_name='grievance_events')
    op.drop_index(op.f('ix_grievance_events_created_at'), table_name='grievance_events')
    op.drop_table('grievance_events')
    # ### end Alembic commands ###
