"""add registration requests

Revision ID: b4d9b6474099
Revises: 9a7efc2bf349
Create Date: 2026-08-30 10:33:58.541910
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b4d9b6474099'
down_revision: Union[str, None] = '9a7efc2bf349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('claimed_ward', sa.Integer(), nullable=True),
    sa.Column('claimed_citizen_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('village_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('matched_citizen_id', sa.String(length=64), nullable=True),
    sa.Column('reviewed_by_id', sa.String(length=64), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matched_citizen_id'], ['citizens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_requests_created_at'), 'registration_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_registration_requests_email'), 'registration_requests', ['email'], unique=False)
    op.create_index(op.f('ix_registration_requests_status'), 'registration_requests', ['status'], unique=False)
    op.create_index(op.f('ix_registration_requests_village_id'), 'registration_requests', ['village_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_requests_village_id'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_status'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_email'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_created_at'), table_name='registration_requests')
    op.drop_table('registration_requests')
    # ### end Alembic commands ###
