"""add administrative hierarchy and village scoping

Revision ID: be377a6e8c27
Revises: 0eac4115262c
Create Date: 2026-08-30 05:06:42.263281
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'be377a6e8c27'
down_revision: Union[str, None] = '0eac4115262c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the state / district / block / village hierarchy from India's Local
    Government Directory, and scope every village-level record to a village.

    The village_id columns are nullable, so existing rows survive the upgrade;
    `python -m app.seed` then assigns them to the home village.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_mr', sa.String(length=120), nullable=False),
    sa.Column('lgd_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lgd_code')
    )
    op.create_table('districts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_mr', sa.String(length=120), nullable=False),
    sa.Column('lgd_code', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lgd_code')
    )
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_mr', sa.String(length=120), nullable=False),
    sa.Column('lgd_code', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lgd_code')
    )
    op.create_index(op.f('ix_blocks_district_id'), 'blocks', ['district_id'], unique=False)
    op.create_table('villages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_mr', sa.String(length=120), nullable=False),
    sa.Column('lgd_code', sa.Integer(), nullable=True),
    sa.Column('census_code_2011', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('population_2011', sa.Integer(), nullable=True),
    sa.Column('households_2011', sa.Integer(), nullable=True),
    sa.Column('ward_count', sa.Integer(), nullable=False),
    sa.Column('gram_panchayat_status', sa.String(length=48), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_villages_block_id'), 'villages', ['block_id'], unique=False)
    op.create_index(op.f('ix_villages_lgd_code'), 'villages', ['lgd_code'], unique=False)
    op.create_index(op.f('ix_villages_name'), 'villages', ['name'], unique=False)
    op.add_column('citizens', sa.Column('village_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_citizens_village_id'), 'citizens', ['village_id'], unique=False)
    with op.batch_alter_table('citizens') as batch:
        batch.create_foreign_key(
            'fk_citizens_village_id', 'villages', ['village_id'], ['id'], ondelete='CASCADE'
        )
    op.add_column('facilities', sa.Column('village_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_facilities_village_id'), 'facilities', ['village_id'], unique=False)
    with op.batch_alter_table('facilities') as batch:
        batch.create_foreign_key(
            'fk_facilities_village_id', 'villages', ['village_id'], ['id'], ondelete='CASCADE'
        )
    op.add_column('families', sa.Column('village_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_families_village_id'), 'families', ['village_id'], unique=False)
    with op.batch_alter_table('families') as batch:
        batch.create_foreign_key(
            'fk_families_village_id', 'villages', ['village_id'], ['id'], ondelete='CASCADE'
        )
    op.add_column('grievances', sa.Column('village_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_grievances_village_id'), 'grievances', ['village_id'], unique=False)
    with op.batch_alter_table('grievances') as batch:
        batch.create_foreign_key(
            'fk_grievances_village_id', 'villages', ['village_id'], ['id'], ondelete='CASCADE'
        )
    op.add_column('projects', sa.Column('village_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_projects_village_id'), 'projects', ['village_id'], unique=False)
    with op.batch_alter_table('projects') as batch:
        batch.create_foreign_key(
            'fk_projects_village_id', 'villages', ['village_id'], ['id'], ondelete='CASCADE'
        )
    op.add_column('sabha_meetings', sa.Column('village_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_sabha_meetings_village_id'), 'sabha_meetings', ['village_id'], unique=False)
    with op.batch_alter_table('sabha_meetings') as batch:
        batch.create_foreign_key(
            'fk_sabha_meetings_village_id', 'villages', ['village_id'], ['id'], ondelete='CASCADE'
        )
    op.add_column('users', sa.Column('village_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_village_id'), 'users', ['village_id'], unique=False)
    with op.batch_alter_table('users') as batch:
        batch.create_foreign_key(
            'fk_users_village_id', 'villages', ['village_id'], ['id'], ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch:
        batch.drop_constraint('fk_users_village_id', type_='foreignkey')
    op.drop_index(op.f('ix_users_village_id'), table_name='users')
    op.drop_column('users', 'village_id')
    with op.batch_alter_table('sabha_meetings') as batch:
        batch.drop_constraint('fk_sabha_meetings_village_id', type_='foreignkey')
    op.drop_index(op.f('ix_sabha_meetings_village_id'), table_name='sabha_meetings')
    op.drop_column('sabha_meetings', 'village_id')
    with op.batch_alter_table('projects') as batch:
        batch.drop_constraint('fk_projects_village_id', type_='foreignkey')
    op.drop_index(op.f('ix_projects_village_id'), table_name='projects')
    op.drop_column('projects', 'village_id')
    with op.batch_alter_table('grievances') as batch:
        batch.drop_constraint('fk_grievances_village_id', type_='foreignkey')
    op.drop_index(op.f('ix_grievances_village_id'), table_name='grievances')
    op.drop_column('grievances', 'village_id')
    with op.batch_alter_table('families') as batch:
        batch.drop_constraint('fk_families_village_id', type_='foreignkey')
    op.drop_index(op.f('ix_families_village_id'), table_name='families')
    op.drop_column('families', 'village_id')
    with op.batch_alter_table('facilities') as batch:
        batch.drop_constraint('fk_facilities_village_id', type_='foreignkey')
    op.drop_index(op.f('ix_facilities_village_id'), table_name='facilities')
    op.drop_column('facilities', 'village_id')
    with op.batch_alter_table('citizens') as batch:
        batch.drop_constraint('fk_citizens_village_id', type_='foreignkey')
    op.drop_index(op.f('ix_citizens_village_id'), table_name='citizens')
    op.drop_column('citizens', 'village_id')
    op.drop_index(op.f('ix_villages_name'), table_name='villages')
    op.drop_index(op.f('ix_villages_lgd_code'), table_name='villages')
    op.drop_index(op.f('ix_villages_block_id'), table_name='villages')
    op.drop_table('villages')
    op.drop_index(op.f('ix_blocks_district_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_table('states')
    # ### end Alembic commands ###
