"""widen scheme benefit to text

Revision ID: ef791b37d385
Revises: be377a6e8c27
Create Date: 2026-08-30 05:19:08.327935
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef791b37d385'
down_revision: Union[str, None] = 'be377a6e8c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Real government benefit text runs past 255 characters — the EBC
    # scholarship alone is 269. Postgres enforces VARCHAR limits; SQLite does
    # not, which is why the test suite did not catch this.
    with op.batch_alter_table('schemes') as batch:
        batch.alter_column('benefit', existing_type=sa.VARCHAR(length=255),
                           type_=sa.Text(), existing_nullable=False)
        batch.alter_column('benefit_mr', existing_type=sa.VARCHAR(length=255),
                           type_=sa.Text(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schemes') as batch:
        batch.alter_column('benefit_mr', existing_type=sa.Text(),
                           type_=sa.VARCHAR(length=255), existing_nullable=False)
        batch.alter_column('benefit', existing_type=sa.Text(),
                           type_=sa.VARCHAR(length=255), existing_nullable=False)
    # ### end Alembic commands ###
