"""Generate placeholder PDFs for seeded documents.

Seeded document rows used to have no file behind them, so the officer's
verification screen could show the record but never the document. Approving a
certificate you cannot read is not verification, and requiring a reason for
rejection means nothing when there is nothing to form a reason about.

These are written by hand as minimal PDFs rather than with a library, because
the point is a page that opens in any viewer, and a dependency is a poor trade
for forty lines.

Every page says, in large type, that it is sample data. Nobody should be able
to screenshot one of these and pass it off as a real income certificate, and
a file that looked like a genuine government document would be exactly the
kind of thing this project has no business producing.
"""

from __future__ import annotations

from pathlib import Path


def _escape(text: str) -> str:
    """Escape the three characters that are syntax inside a PDF string."""
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def build_pdf(lines: list[tuple[str, int, int]]) -> bytes:
    """A one-page A4 PDF. Each line is (text, font size, y position)."""
    parts = ["BT"]
    for text, size, y in lines:
        parts.append(f"/F1 {size} Tf")
        parts.append(f"1 0 0 1 60 {y} Tm")
        parts.append(f"({_escape(text)}) Tj")
    parts.append("ET")
    stream = "\n".join(parts).encode("latin-1", errors="replace")

    objects: list[bytes] = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + body + b"\nendobj\n"

    xref_at = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for offset in offsets[1:]:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_at}\n%%EOF\n"
    ).encode()
    return bytes(out)


def sample_document(
    doc_type: str,
    citizen_name: str,
    citizen_id: str,
    submitted: str,
) -> bytes:
    """A clearly-marked placeholder standing in for a real certificate."""
    return build_pdf(
        [
            ("SAMPLE DOCUMENT - NOT A REAL CERTIFICATE", 15, 780),
            ("Generated by the E-Panchayat demo seed. It carries no", 10, 758),
            ("legal weight and certifies nothing.", 10, 744),
            (doc_type, 20, 690),
            (f"Resident: {citizen_name}", 12, 650),
            (f"Record ID: {citizen_id}", 12, 630),
            (f"Submitted: {submitted}", 12, 610),
            ("Loni Kalbhor Gram Panchayat", 12, 570),
            ("Haveli block, Pune district, Maharashtra", 11, 552),
            ("This page exists so the document verification screen has", 10, 500),
            ("something to open. A real deployment would hold the", 10, 486),
            ("resident's actual uploaded certificate here.", 10, 472),
        ]
    )


def write_sample(
    root: Path,
    citizen_id: str,
    doc_id: str,
    doc_type: str,
    citizen_name: str,
    submitted: str,
) -> tuple[Path, int]:
    """Write one placeholder and return its path and size."""
    target_dir = root / citizen_id
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / f"{doc_id}.pdf"
    payload = sample_document(doc_type, citizen_name, citizen_id, submitted)
    target.write_bytes(payload)
    return target, len(payload)
